name: pr_check

on: [push, pull_request]

jobs:
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: yarn install && yarn add enzyme @wojtekmaj/enzyme-adapter-react-17 puppeteer

      - name: test:unit
        run: cd packages/concis-react && yarn install && yarn test:unit
